seven_seg.h
muhlbaier/embedded-software pull request #26
Opened 2019-03-27 01:12 UTC by msorce26

Add seven_seg.h file.

2019-03-28 10:08 UTC, muhlbaier requested changes
Great job overall just needs a couple tweaks. Also, ask the expected users if they will need to show decimal numbers (if yes will they ever be negative?) and if so add a method to display a number in decimal or add a helper function to do a binary to BCD conversion.

2019-03-28 10:08 UTC, muhlbaier commented on include/seven_seg.h
> + * @Authors: Michael Sorce, Alex Marino, Michael Maloney, and David Gaffney
@Authors doesn't exist in Doxygen, use @author multiple times for each author

2019-03-28 10:08 UTC, muhlbaier commented on include/seven_seg.h
> + * How To Use Module: Call SevenSeg_Init() to initialize the module.
consider adding example code using @code and @endcode tags

2019-03-28 10:08 UTC, muhlbaier commented on include/seven_seg.h
> +#endif /* _SEVEN_SEG_H_ */
missing new line at end of file

2019-04-08 20:05 UTC, msorce26 commented
Requested changes have been made to seven_seg.h. Files seven_seg.c, hal_seven_seg.h, and hal_seven_seg.c have been added.

2019-04-09 12:03 UTC, muhlbaier approved these changes
Good work

2019-04-09 12:04 UTC, merged