Created buzzer module header file
muhlbaier/embedded-software pull request #28
Opened 2019-03-27 02:05 UTC by nikolakosaric

Still need to develop the .c file

2019-03-28 10:03 UTC, muhlbaier requested changes

2019-03-28 10:03 UTC, muhlbaier commented on include/buzzer.h
> +#include "hal_general.h"
You don't need to include hal_general.h here and you certainly don't need it twice

2019-03-28 10:03 UTC, muhlbaier commented on include/buzzer.h
> +
missing @} for doxygen

2019-03-28 10:03 UTC, muhlbaier commented on include/buzzer.h
> +/** @brief
Add brief documentation

2019-03-28 10:03 UTC, muhlbaier commented on include/buzzer.h
> + * @defgroup buzzer_module Buzzer Module
expand the module documentation and include a list of dependent modules (i.e. Timing and Task)

2019-04-02 23:21 UTC, nikolakosaric commented
I've revised the header file based on the comments made above. As the module is developed, the documentation will be referenced and corrected if need be

2019-04-09 12:07 UTC, muhlbaier approved these changes
Looks good.

2019-04-09 12:07 UTC, merged